[package]
org = "ballerinax"
name = "postgresql.driver"
version = "1.7.0"
authors = ["Ballerina"]
keywords = ["Vendor/PostgreSQL", "Area/Database", "Type/Driver"]
repository = "https://github.com/ballerina-platform/module-ballerinax-postgresql.driver"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.13.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.7.7"
path = "./lib/postgresql-42.7.7.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "postgresql.driver-native"
version = "1.7.0"
path = "../native/build/libs/postgresql.driver-native-1.7.0-SNAPSHOT.jar"
